[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robot_framework"
version = "0.0.1"
authors = [
  { name="ITK Development", email="itk-rpa@mkb.aarhus.dk" },
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
]
license = "MIT"
dependencies = [
    "OpenOrchestrator == 2.*",
    "Pillow == 10.*",
    "itk-dev-shared-components == 2.*",
    "python-serviceplatformen==3.*",
    "hvac == 2.*",
    "itk_dev_event_log == 1.*",
    "python-docx==1.*",
    "docxtpl >= 0.2",
]

[project.optional-dependencies]
dev = [
  "pylint",
  "flake8"
]
